spark.master                                  spark://spark-incidents-master:7077
spark.driver.host                             spark-incidents-jupyter
spark.driver.bindAddress                      0.0.0.0
spark.executor.cores                          1
spark.executor.memory                         1g
spark.cores.max                               2
spark.default.parallelism                     4
spark.sql.shuffle.partitions                  8

spark.ui.enabled                              true
spark.ui.retainedJobs                         100
spark.ui.retainedStages                       200

spark.eventLog.enabled                        true
spark.eventLog.dir                            file:/spark-events

spark.sql.adaptive.enabled                    true
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.autoBroadcastJoinThreshold          10m

spark.hadoop.fs.s3a.endpoint                  http://spark-incidents-minio:9000
spark.hadoop.fs.s3a.path.style.access          true
spark.hadoop.fs.s3a.connection.ssl.enabled    false
spark.hadoop.fs.s3a.impl                      org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider  com.amazonaws.auth.EnvironmentVariableCredentialsProvider
